### ISSUE TITLE
Support for Github Enterprise API

### ISSUE THREAD

**Issue by mzmousa** [SamyPesse/octocat.js#6]
I want to be able to use [Github Enterprise API endpoints](https://developer.github.com/v3/enterprise/) like this `http(s)://hostname/api/v3/`. Currently, my way of doing it is something like so: in `lib/index.js`, do:
`uri = this.opts.endpoint + method;` instead of `uri = url.resolve(this.opts.endpoint, method);`
Essentially, the `/api/v3` gets thrown away by the `url.resolve`.

**Comment by taylorc93** [comment]
Just submitted a PR that should fix this, hopefully it'll be taken care of soon!
